### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by cqneosun** [RTCGA/RTCGA#111]
* installing *source* package 'RTCGA' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'mnormt'
ERROR: lazy loading failed for package 'RTCGA'
* removing 'C:/Program Files/R/R-3.4.0/library/RTCGA'

**Comment by MarcinKosinski** [comment]
@cqneosun what happens if you prior install the mnormt package and then RTCGA?

**Comment by cqneosun** [comment]
Thanks.It works with a error:
replacing previous import ‘ggplot2::%+%’ by ‘survminer::%+%’ when loading ‘RTCGA’ 
What does this mean?

**Comment by MarcinKosinski** [comment]
This is not an error. This is a warning.
This means that when you RTCGA you also import some functionality from
survminer package that overwrites the `%+%` operator from ggplot2.
