### ISSUE TITLE
How to deal with the error:Error in dirname(name) : path too long

### ISSUE THREAD

**Issue by cqneosun** [RTCGA/RTCGA#113]
trying URL 'http://gdac.broadinstitute.org/runs/stddata__2016_01_28/data/LUAD/20160128/gdac.broadinstitute.org_LUAD-FFPE.Merge_methylation__humanmethylation450__jhu_usc_edu__Level_3__within_bioassay_data_set_function__data.Level_3.2016012800.0.0.tar.gz'
Content type 'application/x-gzip' length 55470161 bytes (52.9 MB)
downloaded 52.9 MB

Error in dirname(name) : path too long

**Comment by MarcinKosinski** [comment]
@cqneosun I guess you might be using windows.

but which RTCGA version were you using and which function call?

I guess this ight be outdated due to lack of the information here
