### ISSUE TITLE
Inconsistent Sample Identifiers

### ISSUE THREAD

**Issue by DarioS** [RTCGA/RTCGA#114]
Some sample have been identified as being of a different cancer type in [Notifications](http://gdac.broadinstitute.org/runs/sampleReports/latest/SKCM_Notifications.html).

Strangely, some RTCGA data packages have the updated identifiers whereas others have the old identifiers.

```
library(RTCGA.rnaseq)
library(RTCGA.mutations)
changed <- c("TCGA-D9-A1X", "TCGA-D9-A4Z6", "TCGA-HR-A2OG", "TCGA-HR-A2OH")
unname(sapply(changed, grep, as.character(SKCM.rnaseq[, 1]), value = TRUE))
[1] "TCGA-D9-A1X3-06A-11R-A18S-07" "TCGA-D9-A4Z6-06A-12R-A266-07" "TCGA-HR-A2OG-06A-21R-A18U-07" "TCGA-HR-A2OH-06A-11R-A18U-07"
unique(unlist(lapply(changed, grep, as.character(SKCM.mutations[, "Tumor_Sample_Barcode"]), value = TRUE)))
[1] "TCGA-D9-A1X3-01A-11D-A197-08" "TCGA-D9-A4Z6-01A-12D-A25O-08" "TCGA-HR-A2OG-01A-21D-A197-08" "TCGA-HR-A2OH-01A-11D-A197-08"
```

Note that the RNA-seq dataset represents these four samples as metastatic cancers, but the mutations dataset represents them as primary cancers. This discrepancy makes cross-matching sample between tables annoying.

**Comment by MarcinKosinski** [comment]
@DarioS I don't know if I got notification for this message. Please tag @MarcinKosinski next time. Thanks

**Comment by MarcinKosinski** [comment]
@DarioS what about 

`substr(as.character(SKCM.mutations[, "Tumor_Sample_Barcode"]), 1, 12)` ? and also for rnaseq for joining?

**Comment by DarioS** [comment]
I suppose that's a decent workaround.
