### ISSUE TITLE
Can not install RTCGA.mutations.20160128

### ISSUE THREAD

**Issue by xiefe** [RTCGA/RTCGA#115]
### Expected behavior 
I'd like to install the latest mutation package `RTCGA.mutations.20160128`, but there is an error when installing the package through  `biocLite('RTCGA.mutations.20160128')` or `installTCGA("RTCGA.mutations.20160128")`
### Actual behavior

When I try to install through `biocLite('RTCGA.mutations.20160128')`, I got the error:
```
Warning message:
package ‘RTCGA.mutations.20160128’ is not available (for R version 3.3.2) 
```

Through `installTCGA("RTCGA.mutations.20160128")`
```
> installTCGA("RTCGA.mutations.20160128")
Error in stop(assertError(attr(res, "msg"))) : bad error message
```
Would you please help me to install the package?
### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by MarcinKosinski** [comment]
@xiefe this package is only available on GitHub right now. Try

```
devtools::install_github('RTCGA/RTCGA.mutations.20160128')
```
