### ISSUE TITLE
Some cancer type data cannot download.

### ISSUE THREAD

**Issue by seedson** [RTCGA/RTCGA#121]
### Expected behavior 
I can download LUAD,LUSC,OV,but ACC ,ESCC and so on can not be downloaded.
### Actual behavior
What I Type:

expr <- expressionsTCGA(ACC.mRNA, extract.cols = c("GATA3", "PTEN", "XBP1","ESR1", "MUC1"))

What it shown:

Error in expressionsTCGA(ACC.mRNA, extract.cols = c("GATA3", "PTEN", "XBP1",  : 
  object 'ACC.mRNA' not found

**Comment by MarcinKosinski** [comment]
@seedson have you tried 
```{R}
library(RTCGA.mRNA)
data(ACC.mRNA)
````
 first and then 
```{R}
èxpr <- expressionsTCGA(ACC.mRNA, extract.cols = c("GATA3", "PTEN", "XBP1","ESR1", "MUC1"))
```

You need to load the data from the package, so it can be used
