### ISSUE TITLE
Survival data information maybe outdated?

### ISSUE THREAD

**Issue by hsiowa2** [RTCGA/RTCGA#122]
Hello.

First of all, thank you for the great package. 

I was trying to perform survival analysis, but it seems that the follow-up time ("times" category in the result of survivalTCGA function) of some patient is different from the homepage of TCGA.

For example, the patient TCGA-3A-A9IR has the follow-up time of 1542 days in the homepage of TCGA, but when I checked the "times" category in survivalTCGA function it said 1164. 

It looks like this happens to some patients, while other patients are okay (match with the information in TCGA). Do you have any ideas about why this is happening?

Thank you very much.

**Comment by MarcinKosinski** [comment]
closing because this is outdated
