### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by JuliaArizanova** [RTCGA/RTCGA#124]
### Expected behavior 

Hi, 

Thank you very much for the wonderful package! 
I am hoping to access DFS (disease-free survival) data for the PRAD cohort. I wanted to ask if this data is available within the package? I have tried looking for it using the following:

PRAD.clinical[grepl("dfs", colnames(PRAD.clinical))]
PRAD.clinical[grepl("disease_free", colnames(PRAD.clinical))]

But I haven't had any luck.

### `session_info()`

````{R}
# please paste here the result of
devtools::session_info()
````

**Comment by MarcinKosinski** [comment]
i dont know
