### ISSUE TITLE
Capital letters in names of packages

### ISSUE THREAD

**Issue by pbiecek** [RTCGA/RTCGA#18]
Maybe it's too late for that, 
but for miRNA, RNAseq, CNV it's common to use capital letters for abbreviations
In RTCGA.mirna it's not clear why first letters are capital and other are note

**Comment by MarcinKosinski** [comment]
RPPA, CNV and miRNA are submitted to bioconductor with capital letters in names. I also changed object's names in those packages that they will have capital names at the end.

I also send a request to bioconductor-devel mailing list to change the name of RTCGA.rnaseq package to RTCGA.RNASeq - there is a slight possibility to do this.
