### ISSUE TITLE
local biocchecks for all data packages

### ISSUE THREAD

**Issue by wchodor** [RTCGA/RTCGA#27]

**Comment by MarcinKosinski** [comment]
@wchodor  would you be so kind and install https://bioconductor.org/packages/release/bioc/html/BiocCheck.html package and to perform a BiocCheck() for `RTCGA.mRNA` , `RTCGA.miRNASeq` and `RTCGA.RPPA` ?

**Comment by MarcinKosinski** [comment]
done and submitted them here: https://tracker.bioconductor.org/issue1335
