### ISSUE TITLE
Shiny webapp for gene expression

### ISSUE THREAD

**Issue by pbiecek** [RTCGA/RTCGA#31]
based on RTCGA.mRNA
see more here
http://mi2.mini.pw.edu.pl:8080/RTCGA/MMM/shiny/

Maybe could be referenced on main page of RTCGA.mRNA package of RTCGA package?

More will follow

**Comment by MarcinKosinski** [comment]
It this is finished it can be linked in the `README.md` of RTCGA/RTCGA.mRNA and `README.md` of RTCGA/RTCGA. It'll be best if authors of this app could provide PR to both packages.

**Comment by MarcinKosinski** [comment]
By the way, looks very impresive.

**Comment by MarcinKosinski** [comment]
I am planning to add RTCGA poster from ISOBM conference (in relevant version)  as one of vignettes and planning to send it as an announcement on bioconductor-devel mailing list. After we create functionalities needed for the bioinformatics-article. With the announcement mail I also can provide links to those applications if authors agreed.

**Comment by MarcinKosinski** [comment]
#34

**Comment by pbiecek** [comment]
Here are source codes
https://github.com/pbiecek/WarsztatyBadawcze/tree/master/zespoly

This app is here:
https://github.com/pbiecek/WarsztatyBadawcze/tree/master/zespoly/MMM/shiny
(there will be more apps)

Yes, the app is very nice, they did good job.


2016-02-08 23:00 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> By the way, looks very impresive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/31#issuecomment-181577686>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
It'll be good to have `README.md` in the folder of each team with the short description in english. It might be problematic. Moreover what would you say about short description of workshops in english?

**Comment by pbiecek** [comment]
hmm,
let's wait for other apps and we will see what to do.

They shall come with overview like this one:
https://github.com/pbiecek/WarsztatyBadawcze/blob/master/zespoly/MMM/report/Report_%20MMM.pdf

So potentially some of them could be a separate short research articles
(like application notes),
or could serve as use cases.

I can prepare a short overview/introduction,
but first let's see other apps.



2016-02-08 23:33 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> It'll be good to have README.md in the folder of each team with the short
> description in english. It might be problematic. Moreover what would you
> say about short description of workshops in english?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/31#issuecomment-181597170>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment]
Ok,
so we have two completed Shiny apps related to gene expression,
they are here:
http://mi2.mini.pw.edu.pl:8080/RTCGA/MMM/shiny/
http://mi2.mini.pw.edu.pl:8080/RTCGA/KRWK/shiny/

Maybe the can be embedded in an iframe in the RTCGA page?
I think that both of them are pretty nice illustrations of what can be done with TCGA + R

**Comment by MarcinKosinski** [comment]
They look like a piece of great work. Is embedding shiny apps in IFrame a hard issue?

Marcin Kosinski

Dnia 14.02.2016 o godz. 20:55 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
It's should be easy (in most cases), just add this html instruction to the html code

<IFRAME SRC="http://mi2.mini.pw.edu.pl:8080/RTCGA/KRWK/shiny/" WIDTH=1000 HEIGHT=800>
If you can see this, your browser doesn't 
understand IFRAME.  However, we'll still 
<A HREF="http://mi2.mini.pw.edu.pl:8080/RTCGA/KRWK/shiny/">link</A> 
you to the file.
</IFRAME>

**Comment by pbiecek** [comment]
<iframe width="1000" height="800" src="http://mi2.mini.pw.edu.pl:8080/RTCGA/KRWK/shiny/" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

**Comment by pbiecek** [comment]
It turns out that it's not trivial on github.

The almost working example is here:
https://github.com/RTCGA/RTCGA/blob/master/vignettes/README.html

Tendered to 
https://rawgit.com/RTCGA/RTCGA/master/vignettes/README.html

Almost, because mi2 server does not support https protocol yet
I will ask admins to fix this

**Comment by pbiecek** [comment]
Bad news, it's not a problem with mi2 server, but with shiny.
The open free version does not support SSL
I will apply for full version of shiny https://www.rstudio.com/pricing/academic-pricing/
and we will see

**Comment by pbiecek** [comment]
Ok, maybe there is a hope with forwarding done by tophat/apache 
as here http://www.r-bloggers.com/shiny-https-securing-shiny-open-source-with-ssl/
I will talk with admins

**Comment by MarcinKosinski** [comment]
So what can we do with such an applications? I can extend `README.md` file with links to them, or authors can provide PR?

**Comment by MarcinKosinski** [comment]
What are the final determination as to #44 #45  and #46  ?

**Comment by MarcinKosinski** [comment]
I have uploaded an image of this application on RTCGA website:
http://rtcga.github.io/RTCGA/Applications.html
with a link under which the application is held.

If such solution suits you, I can link all applications in this way.

**Comment by pbiecek** [comment]
I think it is best possible approach right now.
Looks good.

I will try to run proper https version of shiny but it will take more time.

I am going to show these apps and the RTCGA website during Poznan's
conference.




2016-02-26 18:11 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I have uploaded an image of this application on RTCGA website:
> http://rtcga.github.io/RTCGA/Applications.html
> with a link under which the application is held.
>
> If such solution suits you, I can link all applications in this way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/31#issuecomment-189376591>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Great, thanks!
I am planning to finish the website tommorow.


2016-03-04 10:08 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
I've uploaded pictures of applications to RTCGA website : http://rtcga.github.io/RTCGA/Applications.html there are also links to applications available
