### ISSUE TITLE
Add RTCGA poster to vignettes

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#33]

**Comment by MarcinKosinski** [comment]
So far RTCGA should be enought https://raw.githubusercontent.com/RTCGA/RTCGA/master/RTCGA_workflow_ver3.png

**Comment by pbiecek** [comment]
It's really useful
(had to try it last week)

2016-03-23 15:09 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> So far RTCGA should be enought
> https://raw.githubusercontent.com/RTCGA/RTCGA/master/RTCGA_workflow_ver3.png
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/33#issuecomment-200359563>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Workflow or poster or website :)? 

Marcin Kosinski

Dnia 23.03.2016 o godz. 19:46 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
I was thinking about workflow, but the website is also useful (I can easily
link to web apps)
P

2016-03-23 23:09 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> Workflow or poster or website :)?
>
> Marcin Kosinski
>
> Dnia 23.03.2016 o godz. 19:46 Przemysław Biecek <notifications@github.com>
> napisał(a):
>
> > It's really useful
> > (had to try it last week)
> >
> > 2016-03-23 15:09 GMT+01:00 Marcin Kosiński <notifications@github.com>:
> >
> > > So far RTCGA should be enought
> > >
> https://raw.githubusercontent.com/RTCGA/RTCGA/master/RTCGA_workflow_ver3.png
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/RTCGA/RTCGA/issues/33#issuecomment-200359563>
> > >
> >
> >
> >
> > --
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/33#issuecomment-200563990>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek
