### ISSUE TITLE
add extract survival function for RTCGA.clinical

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#35]

**Comment by MarcinKosinski** [comment]
@pbiecek Could you have a look wheter such functionality for extracting survival data for KMplots looks fine?

Normally I was using `survMisc:::autoplot.survfit` for creating km-plots with risk-tables below but this package has been removed from CRAN. I have found one new package (with few minor issues https://github.com/kassambara/survminer/issues/2 https://github.com/kassambara/survminer/issues/1 ) that more-or-less do the same, so I don't think we need to implement our own `kmPLOT` function 

````{R}
## Extracting Survival Data
library(RTCGA.clinical)
survivalTCGA(BRCA.clinical, OV.clinical, extract.cols = "admin.disease_code") -> BRCAOV.survInfo
library(dplyr)
survivalTCGA(HNSC.clinical, 
   extract.cols = c("patient.drugs.drug.therapy_types.therapy_type",
   								 "admin.disease_code")) %>%
   filter(patient.drugs.drug.therapy_types.therapy_type ==
          "chemotherapy")-> HNSC.survInfo
          
## Kaplan-Meier Survival Curves
library(survminer)
library(survival)
ggsurvplot(survfit(Surv(times, patient.vital_status)~admin.disease_code,
									 data = BRCAOV.survInfo),
				 risk.table = TRUE,
					 ggtheme = theme_RTCGA(base_size = 16,
					 											 base_family = "serif"),
					 break.time.by = 800,
					 palette = c("#FF9E29", "#86AA00"))
````

**Comment by pbiecek** [comment]
Few thoughts,

1. tricks with deparse are nice, but maybe list of cancers can be provided
in a more straightforward way. Like survivalTCGA(cancers=c("BRCA", "OV",
"LUAD"), ...)

The ggsurvplot from survminer is pretty cool. But still I would add a
wrapper over it, to make it easier to use for nonprogrammer (think about
people with biological background).
The we can have a wrapper like:
plotSurvivalTCGA(cancers=c("BRCA", "OV", "LUAD"),
groups="admin.disease_code")

2. it looks like large part of code is in both parts of if statement
(mapply, part of dplyr). maybe this code can be simplified. The smaller the
better.

3. in software engineering there is a rule - no function should be longer
than one page. Maybe we should use this rule as well (shorter functions are
easier to reuse, understand and fix?




2016-02-10 18:02 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> Could you have a look wheter such
> functionality for extracting survival data for KMplots looks fine?
>
> Normally I was using survMisc:::autoplot.survfit for creating km-plots
> with risk-tables below but this package has been removed from CRAN. I have
> found one new package (with few minor issues kassambara/survminer#2
> <https://github.com/kassambara/survminer/issues/2> kassambara/survminer#1
> <https://github.com/kassambara/survminer/issues/1> ) that more-or-less do
> the same, so I don't think we need to implement our own kmPLOT function
>
> ## Extracting Survival Data
> library(RTCGA.clinical)
> survivalTCGA(BRCA.clinical, OV.clinical, extract.cols = "admin.disease_code") -> BRCAOV.survInfo
> library(dplyr)
> survivalTCGA(HNSC.clinical,
>    extract.cols = c("patient.drugs.drug.therapy_types.therapy_type",
>                                  "admin.disease_code")) %>%
>    filter(patient.drugs.drug.therapy_types.therapy_type ==
>           "chemotherapy")-> HNSC.survInfo
> ## Kaplan-Meier Survival Curves
> library(survminer)
> library(survival)
> ggsurvplot(survfit(Surv(times, patient.vital_status)~admin.disease_code,
>                                      data = BRCAOV.survInfo),
>                  risk.table = TRUE,
>                      ggtheme = theme_RTCGA(base_size = 16,
>                                                                  base_family = "serif"),
>                      break.time.by = 800,
>                      palette = c("#FF9E29", "#86AA00"))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/35#issuecomment-182481134>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Thanks for comments,

2016-02-11 1:12 GMT+01:00 Przemysław Biecek <notifications@github.com>:

> Few thoughts,
>
> 1. tricks with deparse are nice, but maybe list of cancers can be provided
> in a more straightforward way. Like survivalTCGA(cancers=c("BRCA", "OV",
> "LUAD"), ...)
>

In this way this function will not work for data.frames that were somehow
changed.
Imagine a situation that one filters `BRCA.clinical` for chemo therapy only
and then he uses this object in
survivalTCGA(BRCA.clinical.filtered, OV.clinical.munged3times)

In a way we provide characters it will not work. More over I'm not sure
whether using `data()`function inside any funcion is legal for CRAN CHECK
(like here:
https://github.com/RTCGA/RTCGA/blob/master/devel/RTCGA.tools/R/cnv_gene_scores.R#L22
)


>
> The ggsurvplot from survminer is pretty cool. But still I would add a
> wrapper over it, to make it easier to use for nonprogrammer (think about
> people with biological background).
> The we can have a wrapper like:
> plotSurvivalTCGA(cancers=c("BRCA", "OV", "LUAD"),
> groups="admin.disease_code")
>
>
So maybe a special plot.method for `survivalTCGA` class, with additional
`groups`/something parameter?
Would look better than plotSurvivalTCGA and survivalTCGA names existing
silmutonusly :)


>
> 2. it looks like large part of code is in both parts of if statement
> (mapply, part of dplyr). maybe this code can be simplified. The smaller the
> better.
>

To fix / To do


>
> 3. in software engineering there is a rule - no function should be longer
> than one page. Maybe we should use this rule as well (shorter functions are
> easier to reuse, understand and fix?
>
>
Let's stick to the rule that no function should be longer than x lines? x =
50 :) ?

**Comment by pbiecek** [comment]
Ad 1: you have convinced me
Ad 3. good constant!

**Comment by MarcinKosinski** [comment]
I have prepared overloaded `plot` method for `survivalTCGA` object which is a result of `survivalTCGA` function. But it looks like one can not use any dplyr operations further since `mutate` and `filter` changes attributes/class of the previous objects to be a regular data.frame..

````{R}
> library(RTCGA.clinical)
> survivalTCGA(BRCA.clinical, OV.clinical, extract.cols = "admin.disease_code") -> BRCAOV.survInfo
> library(dplyr)
> 
> BRCA.clinical %>%
+     filter(patient.drugs.drug.therapy_types.therapy_type %in%
+                c("chemotherapy", "hormone therapy")) %>%
+     rename(therapy = patient.drugs.drug.therapy_types.therapy_type) %>%
+     survivalTCGA(BRCA.clinical, 
+                  extract.cols = c("therapy"))  -> BRCA.survInfo.chemo
> 
> ## Kaplan-Meier Survival Curves
> plot(BRCAOV.survInfo)
Warning message:
Removed 1 rows containing missing values (geom_point). 
> 
> 
> plot(BRCA.survInfo.chemo)
Warning messages:
1: Removed 1 rows containing missing values (geom_point). 
2: Removed 2 rows containing missing values (geom_text). 
> class(BRCA.survInfo.chemo)
[1] "survivalTCGA" "data.frame"  
> 
> plot(BRCA.survInfo.chemo %>%
+          mutate(tim = times), times = "tim")
Error in plot.window(...) : need finite 'xlim' values
In addition: There were 13 warnings (use warnings() to see them)
> 
> class(BRCA.survInfo.chemo %>%
+           mutate(tim = times))
[1] "data.frame"
````

**Comment by MarcinKosinski** [comment]
It might look like we would have to have additional `plot_something` function instead of overloaded plot method. But I'm not happy about that

**Comment by MarcinKosinski** [comment]
Ok I'll go this way:

- `survivalTCGA` for extracting survival data
- `kmTCGA` for plotting survival curves form a data.frame

**Comment by pbiecek** [comment]
Sounds good, 
let me know when there will be functions ready to play with.

**Comment by MarcinKosinski** [comment]
Ok we have now `survivalTCGA` and `kmTCGA` function

One can check examples: 

````{R}
## Extracting Survival Data
library(RTCGA.clinical)
survivalTCGA(BRCA.clinical, OV.clinical, extract.cols = "admin.disease_code") -> BRCAOV.survInfo

# first munge data, then extract survival info
library(dplyr)
BRCA.clinical %>%
    filter(patient.drugs.drug.therapy_types.therapy_type %in%
               c("chemotherapy", "hormone therapy")) %>%
    rename(therapy = patient.drugs.drug.therapy_types.therapy_type) %>%
    survivalTCGA(extract.cols = c("therapy"))  -> BRCA.survInfo.chemo
                 
# first extract survival info, then munge data                  
    survivalTCGA(BRCA.clinical, 
                 extract.cols = c("patient.drugs.drug.therapy_types.therapy_type"))  %>%
    filter(patient.drugs.drug.therapy_types.therapy_type %in%
               c("chemotherapy", "hormone therapy")) %>%
    rename(therapy = patient.drugs.drug.therapy_types.therapy_type) -> BRCA.survInfo.chemo

## Kaplan-Meier Survival Curves
kmTCGA(BRCAOV.survInfo, explanatory.names = "admin.disease_code",  pval = TRUE)

kmTCGA(BRCAOV.survInfo, explanatory.names = "admin.disease_code", main = "",
       xlim = c(0,4000), legend = "right")
 
kmTCGA(BRCA.survInfo.chemo, explanatory.names = "therapy", xlim = c(0, 3000), conf.int = FALSE)
````

Also it is possible for `kmTCGA` to specify `return.survfit` to extract survfit objects from function.
If anybody has any comments or suggestions for improving the documentation or parameters names then feel free to provide a sweet commit.
