### ISSUE TITLE
add theme_RTCGA

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#40]

**Comment by MarcinKosinski** [comment]
@pbiecek I was thinking about RTCGA ggplot theme, which we could provide to have unified plots in our future works, i.e. posters, articles, blogs, articles. There's a little draft of such a theme. Do you think we could make it be more sparkle, shiny and outstanding ?

`theme_RTCGA` as a synonim of `theme_outstanding` :)

**Comment by pbiecek** [comment]
Sounds cool
And I see that you have some specific schemes for colors in mind.
 
From this list:
https://github.com/jrnold/ggthemes
I like pander the most, but would add gridlines.

What are your favourite choices?

**Comment by MarcinKosinski** [comment]
I'll pick few, but by now I'm shocked with
http://mathematica.stackexchange.com/questions/11350/xkcd-style-graphs

2016-02-11 1:44 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by pbiecek** [comment]
Not sure if it's 'publication ready' ;-)

2016-02-11 11:31 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I'll pick few, but by now I'm shocked with
> http://mathematica.stackexchange.com/questions/11350/xkcd-style-graphs
>
> 2016-02-11 1:44 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > Sounds cool
> > And I see that you have some specific schemes for colors in mind.
> >
> > From this list:
> > https://github.com/jrnold/ggthemes
> > I like pander the most, but would add gridlines.
> >
> > What are your favourite choices?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/RTCGA/RTCGA/issues/40#issuecomment-182658645>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/40#issuecomment-182796672>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
scale_*_pander is not so color-blindness free, but the histogram example
looks very nice. 9/10

My other bets are

- theme_igray() + scale_colour_tableau() 9/10
- theme_hc() + scale_colour_hc() 7/10
- theme_gdocs() + scale_color_gdocs() 7/10

2016-02-11 11:43 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Which option then would your prefer?

````{R}

p2 <- ggplot(mtcars, aes(x = wt, y = mpg, colour = factor(gear))) +
    geom_point() +
    ggtitle("Cars")

p2 + theme_pander(gm = FALSE, gM = FALSE) + scale_colour_pander() +
    theme(panel.grid = element_line(), 
          panel.grid.major = element_line(colour = "grey90", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))

p2 + theme_pander(gm = FALSE, gM = TRUE) + scale_colour_pander() +
    theme(panel.grid = element_line(), 
          panel.grid.major = element_line(colour = "grey90", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))


p2 + theme_pander(gm = TRUE, gM = FALSE) + scale_colour_pander() +
    theme(panel.grid = element_line(), 
          panel.grid.major = element_line(colour = "grey90", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))


p2 + theme_pander(gm = TRUE, gM = TRUE) + scale_colour_pander() +
    theme(panel.grid = element_line(), 
          panel.grid.major = element_line(colour = "grey90", size = 0.2),
          panel.grid.minor = element_line(colour = "grey98", size = 0.5))
````

**Comment by pbiecek** [comment]
Good puzzles, 
I spend some time to find out what is different between these plots ;-)

I like the last one the most

**Comment by MarcinKosinski** [comment]
I've updated our `theme_RTCGA` function but I wasn't able to pass `scale_fill/colour_pander()` inside the theme. It's beyond my scope. By now pander colors are commented out. Maybe you know any solution to that?

**Comment by MarcinKosinski** [comment]
http://stackoverflow.com/questions/35559303/r-how-to-add-scale-functio-to-a-theme-object-in-ggplot2
