### ISSUE TITLE
Shiny webapp for methylation

### ISSUE THREAD

**Issue by pbiecek** [RTCGA/RTCGA#45]
As #31 and #44, but this time with methylation data

**Comment by pbiecek** [comment]
And the first app for methylation is here
http://mi2.mini.pw.edu.pl:8080/RTCGA/JF/

maybe we can embed it into an RTCGA website

And there will be second app

**Comment by MarcinKosinski** [comment]
@katarzynaf this shiny application is very elegant. I like those nice icons. I am really amazed.

- Have you considered plotting survival curves with the usage of https://github.com/kassambara/survminer package? Or maybe with `kmTCGA` function https://github.com/RTCGA/RTCGA/issues/35#issuecomment-184329988? In this way you can have risk tables easily :)
- I would really like to have a look at the source of the application, but I think it's not this one https://github.com/katarzynaf/WarsztatyBadawczeAplikacja ? It would be good to add source link somewhere in the app.
- What is more I have found that in the right panel you have `Futher options: ` where is think should be `Further options: `. 
- Does at the last tabPanel :`Biomarkers List` the second inputPanel (with biomarkers)  affects the table output? I think the list covers all biomarkers every time.
- I think `Biomarkers distribution` panel could be extended with the inputClick or inputText that would be responsible for the transformation of biomarkers, such as `log` `log1p` `sqrt` . From my experience sometimes biomarkers distributions are very high and on can see the differences after he or she applies logarithm. 
- I would suggest to use any customized theme from this package to your application https://github.com/jrnold/ggthemes - with small cost you can gain a richer plots.
- Is there any purpose on linking to github URLs in the app and documentation,  where there are actually those packages on Bioconductor: 
     - http://bioconductor.org/packages/RTCGA/
     - http://bioconductor.org/packages/RTCGA.methylation/

To sum up: GREAT JOB :)

**Comment by pbiecek** [comment]
Source codes should be here:
https://github.com/pbiecek/WarsztatyBadawcze/tree/master/zespoly

**Comment by pbiecek** [comment]
The second app that is using the methylation dataset is here:
http://mi2.mini.pw.edu.pl:8080/RTCGA/ASPP/shiny/

**Comment by katarzynaf** [comment]
@MarcinKosinski:
thanks for your valuable feedback :) Creating icons was my favourite part of this :D

1. Packages for plotting survival curves you've mentioned are not known for me - unfortunately. Thanks for references though.
2. Source code has already been up-to-date. You can find it right where @pbiecek said it is.
3. My mistake, already corrected.
4. Yes, that's true. The last tabPanel was created to list all biomarkers. You can use `Search` area (in mainPanel) to find your favourite biomarker :)
5. I'm going to consider your solutions, especially adding transformations in `Biomarkers distribution` sounds like great idea.
6. I'm not sure about the last your point: I thought that both destinations of the RTCGA package are equally important :P 

Thanks again!

**Comment by MarcinKosinski** [comment]
I've uploaded pictures of applications to RTCGA website : http://rtcga.github.io/RTCGA/Applications.html there are also links to applications available
