### ISSUE TITLE
Shiny webapp for protein exprssion

### ISSUE THREAD

**Issue by pbiecek** [RTCGA/RTCGA#46]
based on RPPA data

**Comment by pbiecek** [comment]
Here is first one: http://mi2.mini.pw.edu.pl:8080/RTCGA/ASMC/

**Comment by MarcinKosinski** [comment]
@wchodor have you seen this :)?

**Comment by MarcinKosinski** [comment]
I've uploaded pictures of applications to RTCGA website : http://rtcga.github.io/RTCGA/Applications.html there are also links to applications available
