### ISSUE TITLE
can't install devtools in R for RTCGA

### ISSUE THREAD

**Issue by DecodeGenome** [RTCGA/RTCGA#49]
I try to use this code to install RTCGA package, but warning message: there is no devtools package. how to solve this problem? thanks.

if (!require(devtools)) {
  install.packages("devtools")
  library(devtools)
}
install_github("RTCGA/RTCGA")

**Comment by MarcinKosinski** [comment]
I would appreciate if you'd post the whole output of this line but I assume that you have encountered such a warning

````{R}
> require(devtools)
Loading required package: devtools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
````

This is the case that you didn't have devtools pre-installed. Is such case these lines

````{R}
if (!require(devtools)) {
install.packages("devtools")
library(devtools)
}
````

ensure to load devtools or if you don't have this package they ensure to first install this package.

Then the installation from github should work `install_github("RTCGA/RTCGA")`

So if now you can load `devtools` without warning then everything went well.
Pleas check do you have warning with this line

````{R}
library(devtools)
````

And if not then please close issue.
