### ISSUE TITLE
The code for example plot is not reproducible

### ISSUE THREAD

**Issue by DecodeGenome** [RTCGA/RTCGA#50]
expressionTCGA(ACC.rnaseq, BLCA.rnaseq, BRCA.rnaseq, 
+                CESC.rnaseq, CHOL.rnaseq, COAD.rnaseq,
+                COADREAD.rnaseq, DLBC.rnaseq, ESCA.rnaseq,
+                GBMLGG.rnaseq, GBM.rnaseq, HNSC.rnaseq, KICH.rnaseq,
+                KIPAN.rnaseq, KIRC.rnaseq, KIRP.rnaseq, LAML.rnaseq,
+                LGG.rnaseq, LIHC.rnaseq, LUAD.rnaseq, LUSC.rnaseq,                          
+                OV.rnaseq, PAAD.rnaseq, PCPG.rnaseq, PRAD.rnaseq,                       
+                READ.rnaseq, SARC.rnaseq, SKCM.rnaseq, STAD.rnaseq,                             
+                STES.rnaseq, TGCT.rnaseq, THCA.rnaseq, THYM.rnaseq,
+                UCEC.rnaseq, UCS.rnaseq, UVM.rnaseq,
+                extract.cols = "MET|4233") %>%
+   rename(cohort = dataset,
+          MET = `MET|4233`) %>%  
+   filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% #cancer samples
+   ggplot(aes(y = log1p(MET),
+              x = reorder(cohort, log1p(MET), median),
+              fill = reorder(cohort, log1p(MET), median))) + 
+   geom_boxplot() +
+   theme_RTCGA() +
+   coord_flip()
Error in lapply(list(...), nrow) : object 'COADREAD.rnaseq' not found and more...........

**Comment by MarcinKosinski** [comment]
What is your session info ?
What packages do you load first?

I have updated the example code so that it pinpoints which packages should you have: https://github.com/RTCGA/RTCGA/wiki/Examples-and-Applications

Below is the same code:

````{R}
install.packages('devtools')
devtools::install_github('RTCGA/RTCGA') # install RTCGA from github 
library(RTCGA)
installTCGA('RTCGA.rnaseq') # install data package from github
# you can install all RTCGA data with installTCGA()

# load packages that are needed to munge data and visualize them
library(ggplot2)
library(dplyr)
# if you don't have them then you should install them from CRAN
# install.packages(c("ggplot2", "dplyr"))

# load RTCGA.rnaseq package to vizualize RNASeq
library(RTCGA.rnaseq)
# perfrom plot

expressionTCGA(ACC.rnaseq, BLCA.rnaseq, BRCA.rnaseq, 
							 CESC.rnaseq, CHOL.rnaseq, COAD.rnaseq,
							 COADREAD.rnaseq, DLBC.rnaseq, ESCA.rnaseq,
							 GBMLGG.rnaseq, GBM.rnaseq, HNSC.rnaseq, KICH.rnaseq,
							 KIPAN.rnaseq, KIRC.rnaseq, KIRP.rnaseq, LAML.rnaseq,
							 LGG.rnaseq, LIHC.rnaseq, LUAD.rnaseq, LUSC.rnaseq,                          
							 OV.rnaseq, PAAD.rnaseq, PCPG.rnaseq, PRAD.rnaseq,                       
							 READ.rnaseq, SARC.rnaseq, SKCM.rnaseq, STAD.rnaseq,                             
							 STES.rnaseq, TGCT.rnaseq, THCA.rnaseq, THYM.rnaseq,
							 UCEC.rnaseq, UCS.rnaseq, UVM.rnaseq,
							 extract.cols = "MET|4233") %>%
	rename(cohort = dataset,
				 MET = `MET|4233`) %>%  
	filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% #cancer samples
	ggplot(aes(y = log1p(MET),
						 x = reorder(cohort, log1p(MET), median),
						 fill = reorder(cohort, log1p(MET), median))) + 
	geom_boxplot() +
	theme_RTCGA() +
	coord_flip()
````

An then this is reproducible from scratch.
