### ISSUE TITLE
how to find CIC copy number change (deletion) in each type of cancer using RTCGA

### ISSUE THREAD

**Issue by DecodeGenome** [RTCGA/RTCGA#56]
Hi,
Is there a easy way to pull out the gene "CIC" copy number change in each type of cancer using RTCGA? 

Thanks,

Wei

**Comment by MarcinKosinski** [comment]
I'm not sure If I have understood.
You mean `CIC` gene in `RTCGA.rnaseq` datasets or where?

Next time, if you`ll summon me with the command `@MarcinKosinski` - I'll be notified and can react faster to your questions :)

**Comment by MarcinKosinski** [comment]
Or you mean deletion-mutations in gene?

````{R}
library(RTCGA.mutations)
BRCA.mutations[, c("Hugo_Sumbol", "Variant_Classification", "bcr_patient_barcode")]
````

**Comment by MarcinKosinski** [comment]
@DecodeGenome you can reopen this issue if you like. I am closing it as there is no responce from you.
