### ISSUE TITLE
rewrite BigData use case with functions from RTCGA

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#68]

**Comment by MarcinKosinski** [comment]
@pbiecek  what do you think about rewritten use case http://rtcga.github.io/RTCGA/Usecases.html ?

**Comment by pbiecek** [comment]
I think that it can be shorten further

e.g.
instead of

 bcr_patient_barcode <- c(which(grepl('bcr_patient_barcode' , names(clin),
fixed = TRUE)),
                           which(grepl('bcrpatientbarcode' , names(clin),
fixed = TRUE)),
                           which(grepl('bcr.patient.barcode' , names(clin),
fixed = TRUE)))

you can just use

 bcr_patient_barcode <- grep('bcr.?patient.?barcode' , names(clin))

But after removing these 17 grepl() and which() it will be an excellent
use-case.




2016-04-05 22:19 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> what do you think about rewritten
> use case http://rtcga.github.io/RTCGA/Usecases.html ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/68#issuecomment-205973539>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Sory it hasn't updated yet. The updated version of new webpage Have been pushed to repository but the webpage Haven't refreshed yet. 

Could You Please check this tomorrow? I Was sure that the Update process won't take longer than 5 minutes but this time it's taking extremally long 

Marcin Kosinski

Dnia 05.04.2016 o godz. 23:10 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by MarcinKosinski** [comment]
Ok, now it's new edition : http://rtcga.github.io/RTCGA/Usecases.html

**Comment by pbiecek** [comment]
Looks very good. Could you add also results for 2013? There are much larger
differences in number of patients there.

2016-04-06 12:00 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Ok, now it's new edition : http://rtcga.github.io/RTCGA/Usecases.html
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/68#issuecomment-206275829>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
You mean that in graphs like this one
http://rtcga.github.io/RTCGA/figure/source/Usecases/unnamed-chunk-11-1.png
there also should be points for 2013?

They might did not appear due to the `try` in this `for loop` on mine machine

````{R}
  try({
    all <- read_and_joinTCGA(files[i])
    for (j in seq_along(selected)) {
      selectedCat <- cut(all[,selected[j]+4],
    c(-100,median(all[,selected[j]+4], na.rm = TRUE),10^9))
      
      if (min(table(selectedCat)) >= 20) {
        ndf <- data.frame(
         time = all$times,
         event = all$patient.vital_status ==1,
         var = selectedCat
         )
        pvalues[i,j] <- survdiff(Surv(time, event)~var,
        								data=ndf)$chisq
      }
    }

    n[i] <- nrow(all)
    names[i] <- files[i]
  }, silent = TRUE)
````

**Comment by pbiecek** [comment]
They were here:
https://rawgit.com/RTCGA/RTCGA/master/UseCases/issue1.html

Do you have data downloaded for such old releases?

If not, I can compile this use case on dataset that I have downloaded some
time ago.



2016-04-06 21:21 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> You mean that in graphs like this one
> http://rtcga.github.io/RTCGA/figure/source/Usecases/unnamed-chunk-11-1.png
> there also should be points for 2013?
>
> They might did not appear due to the try in this for loop on mine machine
>
>   try({
>     all <- read_and_joinTCGA(files[i])
>     for (j in seq_along(selected)) {
>       selectedCat <- cut(all[,selected[j]+4],
>     c(-100,median(all[,selected[j]+4], na.rm = TRUE),10^9))
>
>       if (min(table(selectedCat)) >= 20) {
>         ndf <- data.frame(
>          time = all$times,
>          event = all$patient.vital_status ==1,
>          var = selectedCat
>          )
>         pvalues[i,j] <- survdiff(Surv(time, event)~var,
>                                         data=ndf)$chisq
>       }
>     }
>
>     n[i] <- nrow(all)
>     names[i] <- files[i]
>   }, silent = TRUE)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/68#issuecomment-206521303>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
I have them.
Probably I have made some mistakes  in the code, and it does not work for
so old releases and `try` does not return results for them. I'll have a
look at the specific data format for those releases from 2013.

2016-04-06 21:25 GMT+02:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
Ok I have added datasets from 2013
http://rtcga.github.io/RTCGA/Usecases.html

**Comment by pbiecek** [comment]
Great,
for some reason the sessionInfo objects are not recorded and I cannot
recover these plots.
But still they looks good.

2016-04-14 18:54 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Ok I have added datasets from 2013
> http://rtcga.github.io/RTCGA/Usecases.html
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/68#issuecomment-210046975>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Maybe archivist.github is not fully ready for the newest archivist changes. I Have plans to post version 0.2 on cran with minit changes so I'll Have a better look at those sessioInfos

Marcin Kosinski

Dnia 14.04.2016 o godz. 23:45 Przemysław Biecek <notifications@github.com> napisał(a):

**Comment by pbiecek** [comment]
Cool,
here I was trying to recover one of these plots and I was unable. Probably
due to differences in ggplot2 versions.

2016-04-15 1:22 GMT+02:00 Marcin Kosiński <notifications@github.com>:

> Maybe archivist.github is not fully ready for the newest archivist
> changes. I Have plans to post version 0.2 on cran with minit changes so
> I'll Have a better look at those sessioInfos
>
> Marcin Kosinski
>
> Dnia 14.04.2016 o godz. 23:45 Przemysław Biecek <notifications@github.com>
> napisał(a):
>
> > Great,
> > for some reason the sessionInfo objects are not recorded and I cannot
> > recover these plots.
> > But still they looks good.
> >
> > 2016-04-14 18:54 GMT+02:00 Marcin Kosiński <notifications@github.com>:
> >
> > > Ok I have added datasets from 2013
> > > http://rtcga.github.io/RTCGA/Usecases.html
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/RTCGA/RTCGA/issues/68#issuecomment-210046975>
> > >
> >
> >
> >
> > --
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RTCGA/RTCGA/issues/68#issuecomment-210200972>
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment]
Mine ggplot2 version : ggplot2_2.1.0

2016-04-15 10:11 GMT+02:00 Przemysław Biecek <notifications@github.com>:

**Comment by MarcinKosinski** [comment]
@pbiecek  Now I see that only 1 plot is archived with 
`archive(.Last.value, alink = TRUE)` but when I download it by its hook

````{R}
archivist::aread('MarcinKosinski/RTCGA_UseCases/f9e884084b84794d762a535f3facec85')
````

[download by click, then click to load to RStudio] I can see that this hook give empty object - no object is loaded to Global Env.

I think this might be caused by using `.Last.value` instead of `addHooksToPrint` for all `ggplot` objects. 

How were you trying to recover these plots?

**Comment by pbiecek** [comment]
It's likely.
I was trying to use
```
archivist::aread('MarcinKosinski/RTCGA_UseCases/f9e884084b84794d762a535f3facec85')
```
got an error. I've assumed that is's a problem with ggplot2 but I agree that it's probably a problem with .Last.value

**Comment by MarcinKosinski** [comment]
@pbiecek Ok I have added `addHookToPrint()` at the beggining and `pushGitHubRepo()` at the end of this use case. Now everyone can download objects from working hooks like here http://rtcga.github.io/RTCGA/Usecases.html#number-of-observations-in-brca--next-releases

Additionaly I have figured out that I have broken RStudio (I thought that knitr-jekyll is making troubles but I was mistaken). Mine `tabulator` character does not equal `2 spaces` :(
