### ISSUE TITLE
jekyll website VS ReadTheDocs

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#75]
@pbiecek what do you think about comparison between our current website and the potential improvement coming from readthedocs.org ? 

Example http://avocado-framework.readthedocs.org/en/latest/index.html

**Comment by pbiecek** [comment]
@MarcinKosinski It looks really nice, but I like the current layout of the website as well.
So, maybe it's good idea for docs for the next project?

**Comment by MarcinKosinski** [comment]
Will try this on `FSelectorRcpp` https://github.com/mi2-warsaw/FSelectorRcpp/issues/11 :)
