### ISSUE TITLE
RTCGA Installation

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#76]
XS WANG writes

>Dear Marcin,

>I am installing the RTCGA package, but I have got the following problem:

>trying URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.2/XML_3.98-1.3.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.2/XML_3.98-1.3.zip'
>In addition: Warning message:
>In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib/3.2/XML_3.98-1.3.zip': HTTP status was '404 Not Found'
>Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘XML’ failed

> I could not complete the installation. Could you please tell me how to resolve the problem?

> Thanks,
> David

Dear David, 

It looks like you are trying to install `RTCGA` package from CRAN (with the usage of `install.packages` function). It can be seen in this message `cannot open URL 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/bin/windows/contrib` .

`RTCGA` package is not available on CRAN. It is available on Bioconductor on on GitHub.

To install `RTCGA` from GitHub use following code:

````{R}
# if you dont have devtools then install this package with `install.packages('devtools')
library(devtools)
devtools::install_github('RTCGA/RTCGA')
````

The same version of `RTCGA` package in available on Bioconductor. The following installation is

````{R}
source("https://bioconductor.org/biocLite.R")
biocLite("BiocInstaller")
BiocInstaller::useDevel()
biocLite('RTCGA')
````

**Comment by davidwangxs2** [comment]
Thanks, Marcin.
