### ISSUE TITLE
add length parameter to untar :P

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#81]

**Comment by MarcinKosinski** [comment]
@Kornel I'll fix this issue with 2long names in files (before and after untarring) so that windows users will have easier files management. My final deadline is may 3rd, because working after may 4th (bioc release) will be almost pointless :)

**Comment by Kornel** [comment]
Perfect. Maybe additionally some output which would inform the poor windows user his path has over 255 characters? 

It might still happen, we have long directories, long filenames, do you plan to change both the filename and directory name?

**Comment by MarcinKosinski** [comment]
I think informing users is a good idea. You rather like warning message or normal `cat` output?
I will shorten directories and filenames so that `folder/file` will not have more than 255 chars

**Comment by Kornel** [comment]
Great. A warning would be appropriate

**Comment by MarcinKosinski** [comment]
@Kornel I've checked that this is only possible to shorten the name of downloaded .tar.gz file. But even though the name of downloaded .tar.gz file is shorter than original, the extraction of directories that are inside the .tar.gz file can not be performed automatically with substraction/substrings.

I recommend workaround like in all (RTCGA.data) vignettes -
https://bioconductor.org/packages/devel/data/experiment/vignettes/RTCGA.clinical/inst/doc/downloading_clinical_datasets.html ->  Shortening paths and directories
