### ISSUE TITLE
closure of TCGA data portal

### ISSUE THREAD

**Issue by vobencha** [RTCGA/RTCGA#91]
Hi all,

I understand the TCGA data portal has closed down and the data have been moved to Genomic Data Commons. This has significant impact on the RTCGA software package. All data packages currently in the experimental data repo depend on this package which is currently broken in release and devel:
  http://www.bioconductor.org/checkResults/devel/bioc-LATEST/
  http://www.bioconductor.org/checkResults/release/bioc-LATEST/

Before we add new data to ExperimentHub the following issues must be fixed:

* RTCGA software package
-- remove code that accesses the old data portal; keep only helper functions that manipulate, display the static data files
-- remove all \dontrun statement in the man pages
-- update all documentation to explain the package now contains only
helpers for static data files

* 9 experimental data packages currently in repo
-- Update vignettes and man pages to indicate old portal is closed down and any code that accesses the old portal is now historical. I would suggest archiving the old vignettes as 'historical' and creating new, minimal documentation of what is possible with the new version of the RTCGA software package.

Valerie

**Comment by MarcinKosinski** [comment]
Thanks Valerie for good ideas :)!

Please next time add `@RTCGA` or maybe `@MarcinKosinski` to your message so that I will get notification on my email immediately. 

I am glad that there is a visible way to finish my journey with RTCGA after I'll provide those 2 updates you have mentioned :)

**Comment by MarcinKosinski** [comment]
@vobencha  RTCGA downloads datasets from Broad Institute where data are still there http://gdac.broadinstitute.org/ and can be still accessed with existing functionality.

For now I will focus on fixing RTCGA () and providing new packages to Experiment Hub (https://github.com/RTCGA/RTCGA/issues/85)
