### ISSUE TITLE
methylation Data - explained: level 3 and platform HM27 

### ISSUE THREAD

**Issue by lemon86** [RTCGA/RTCGA#92]
Hi Dr. Marcin,
    I am interested in the data from R package 'RTCGA.methylation'. Before the analysis, I wonder:
1. whether the methylation data downloaded through 'RTCGA.methylation' is level 3?
2. if there is any way that I can download the methylation data performed on the platform HM450 ?
 I am looking forward to your reply.
Best Wishes.
Fan

**Comment by MarcinKosinski** [comment]
Hi @lemon86 

As stated in the package vignette, in RTCGA.methylation we only have HM27 https://bioconductor.org/packages/release/data/experiment/vignettes/RTCGA.methylation/inst/doc/downloading_methylation_datasets.html

and they were downloaded with such instructions

````{R}
library(RTCGA)
(cohorts <- infoTCGA() %>% 
   rownames() %>% 
   sub("-counts", "", x=.))

#dir.create( "data2" )
releaseDate <- "2015-11-01"
sapply(cohorts,
             function(element){
                try({
downloadTCGA( cancerTypes = element, 
              dataSet = "Merge_methylation__humanmethylation27",
              destDir = "data2", 
              date = releaseDate )
                })
})


````


The description of the package states that (https://github.com/RTCGA/RTCGA.methylation/blob/master/DESCRIPTION) we downloaded data which format is explained here https://wiki.nci.nih.gov/display/TCGA/DNA+methylation where you can find information that HM27 is available in level 1,2 and 3.

It might not be clear which level we provide in RTCGA.methylation as we only used `Merge_methylation__humanmethylation27` term to download datasets but we can check to which dataset name does this short term correspond

````{R}
> library(RTCGA)
> library(dplyr)
> checkTCGA(what = 'DataSets', cancerType = 'BRCA', date = '2015-11-01') %>%
+   filter(grepl('Merge_methylation__humanmethylation27', Name))
  Size                                                                                                                                    Name
1  83M BRCA.Merge_methylation__humanmethylation27__jhu_usc_edu__Level_3__within_bioassay_data_set_function__data.Level_3.2015110100.0.0.tar.gz
````

So this is actually a level 3 dataset.


To work with HM450 you need to substitute `'Merge_methylation__humanmethylation27` with `'Merge_methylation__humanmethylation450` - but those files are too large to be added to the package.
