### ISSUE TITLE
Survival plots against genes expression in RTCGA

### ISSUE THREAD

**Issue by MarcinKosinski** [RTCGA/RTCGA#97]
> Hi Marcin and RTCGA team,

> Thanks a lot for the wonderful RTCGA package. 

> I wanted to know if its possible to use merged clinical data from multiple cancer type to look at survival data for a gene set, I am trying to make KM plots by using dataset for many cancer types at the same time using a set of genes. I am aware that RTCGA package facilitates making Cox hazard model that integrates mutation data with clinical data but that doesn't allow using data from multiple cancer types but allows use of one cancer type at a time. 
I will greatly appreciate any help. Thanks in advance.

**Comment by MarcinKosinski** [comment]
Survival plots for many cancers against genes' expression
================

-   [Data preparation](#data-preparation)
    -   [Data summary statistics](#data-summary-statistics)
    -   [Data pre-processing](#data-pre-processing)
    -   [Joining survival times and genes' expression](#joining-survival-times-and-genes-expression)
-   [Kaplan Meier estimates for survival curves - plots](#kaplan-meier-estimates-for-survival-curves---plots)
    -   [maxstat - maximally selected rank statistics](#maxstat---maximally-selected-rank-statistics)
    -   [Determine the optimal cutpoint of variables](#determine-the-optimal-cutpoint-of-variables)
    -   [Plot cutpoint for ABCC11](#plot-cutpoint-for-abcc11)
    -   [Categorize variables](#categorize-variables)
    -   [Fit survival curves and visualize](#fit-survival-curves-and-visualize)
        -   [RTCGA way](#rtcga-way)
        -   [survminer way](#survminer-way)

Data preparation
================

``` r
# installation
# source("https://bioconductor.org/biocLite.R")
# biocLite("RTCGA.clinical")
# biocLite("RTCGA.rnaseq")
library(RTCGA.clinical) # survival times
library(RTCGA.rnaseq) # genes' expression

library(tidyverse) # pipes (%>%) and dplyr data munging
survivalTCGA(BRCA.clinical, HNSC.clinical) -> BRCA_HNSC.surv
expressionsTCGA(
   BRCA.rnaseq, HNSC.rnaseq,
   extract.cols = c("ABCC11|85320", "ABCD4|5826")
) -> BRCA_HNSC.rnaseq
```

Data summary statistics
-----------------------

``` r
dim(BRCA_HNSC.surv); dim(BRCA_HNSC.rnaseq)
```

    [1] 1625    3

    [1] 1778    4

``` r
head(BRCA_HNSC.surv); head(BRCA_HNSC.rnaseq)
```

      times bcr_patient_barcode patient.vital_status
    1  3767        TCGA-3C-AAAU                    0
    2  3801        TCGA-3C-AALI                    0
    3  1228        TCGA-3C-AALJ                    0
    4  1217        TCGA-3C-AALK                    0
    5   158        TCGA-4H-AAAK                    0
    6  1477        TCGA-5L-AAT0                    0

    # A tibble: 6 × 4
               bcr_patient_barcode     dataset `ABCC11|85320` `ABCD4|5826`
                             <chr>       <chr>          <dbl>        <dbl>
    1 TCGA-3C-AAAU-01A-11R-A41B-07 BRCA.rnaseq        92.0239     322.2560
    2 TCGA-3C-AALI-01A-11R-A41B-07 BRCA.rnaseq      7793.9097     486.6775
    3 TCGA-3C-AALJ-01A-31R-A41B-07 BRCA.rnaseq         0.9066     308.2502
    4 TCGA-3C-AALK-01A-11R-A41B-07 BRCA.rnaseq      2210.1779     589.1601
    5 TCGA-4H-AAAK-01A-12R-A41B-07 BRCA.rnaseq        95.3191     615.7447
    6 TCGA-5L-AAT0-01A-12R-A41B-07 BRCA.rnaseq       402.4050     896.3191

Data pre-processing
-------------------

``` r
BRCA_HNSC.rnaseq <- BRCA_HNSC.rnaseq %>%
   rename(cohort = dataset,
          ABCC11 = `ABCC11|85320`,
          ABCD4 = `ABCD4|5826`) %>%
   filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% 
   # only cancer samples
   mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12))
 
head(BRCA_HNSC.rnaseq)
```

    # A tibble: 6 × 4
      bcr_patient_barcode      cohort    ABCC11    ABCD4
                    <chr>       <chr>     <dbl>    <dbl>
    1        TCGA-3C-AAAU BRCA.rnaseq   92.0239 322.2560
    2        TCGA-3C-AALI BRCA.rnaseq 7793.9097 486.6775
    3        TCGA-3C-AALJ BRCA.rnaseq    0.9066 308.2502
    4        TCGA-3C-AALK BRCA.rnaseq 2210.1779 589.1601
    5        TCGA-4H-AAAK BRCA.rnaseq   95.3191 615.7447
    6        TCGA-5L-AAT0 BRCA.rnaseq  402.4050 896.3191

Joining survival times and genes' expression
--------------------------------------------

``` r
BRCA_HNSC.surv %>%
   left_join(BRCA_HNSC.rnaseq,
             by = "bcr_patient_barcode") ->
   BRCA_HNSC.surv_rnaseq

head(BRCA_HNSC.surv_rnaseq)
```

      times bcr_patient_barcode patient.vital_status      cohort    ABCC11    ABCD4
    1  3767        TCGA-3C-AAAU                    0 BRCA.rnaseq   92.0239 322.2560
    2  3801        TCGA-3C-AALI                    0 BRCA.rnaseq 7793.9097 486.6775
    3  1228        TCGA-3C-AALJ                    0 BRCA.rnaseq    0.9066 308.2502
    4  1217        TCGA-3C-AALK                    0 BRCA.rnaseq 2210.1779 589.1601
    5   158        TCGA-4H-AAAK                    0 BRCA.rnaseq   95.3191 615.7447
    6  1477        TCGA-5L-AAT0                    0 BRCA.rnaseq  402.4050 896.3191

``` r
table(BRCA_HNSC.surv_rnaseq$cohort, useNA = "always")
```


    BRCA.rnaseq HNSC.rnaseq        <NA> 
           1093         519          13 

``` r
# 13 patients have clinicla info but they do not have expression information

BRCA_HNSC.surv_rnaseq <- BRCA_HNSC.surv_rnaseq %>%
   filter(!is.na(cohort))

# complete data
dim(BRCA_HNSC.surv_rnaseq)
```

    [1] 1612    6

Kaplan Meier estimates for survival curves - plots
==================================================

maxstat - maximally selected rank statistics
--------------------------------------------

Since the genes' expression is a continuous variable the survival plot can not be distingushed to groups corresponding to the gene expression. One way to overcome this is to divide a continuous variable into groups. Problems caused by categorization of continuous variables are known and widely spread ([Harrel, 2015](http://biostat.mc.vanderbilt.edu/wiki/Main/CatContinuous)), but in this case there appear an methodology requirement for the discretization.

@kassambara  prepared a functionality that uses the [maxstat(maximally selected rank statistics)](https://cran.r-project.org/web/packages/maxstat/index.html) statistic to determine the optimal cutpoint for continuous variables and provided it in the [survminer](https://cran.rstudio.com/web/packages/survminer/index.html) package. The developmnet process is described on the [survminer issues track](https://github.com/kassambara/survminer/issues)

``` r
#devtools::install_github('kassambara/survminer')
library(survminer)
```

Articles using maxstat:

-   <http://www.haematologica.org/content/99/9/1410>
-   <http://www.bloodjournal.org/content/bloodjournal/120/5/1087.full.pdf>
-   <http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4058021/pdf/oncotarget-05-2487.pdf>
-   <http://www.impactjournals.com/oncotarget/index.php?journal=oncotarget&page=article&op=view&path>\[\]=3237&path\[\]=6227

Determine the optimal cutpoint of variables
-------------------------------------------

``` r
BRCA_HNSC.surv_rnaseq.cut <- surv_cutpoint(
   BRCA_HNSC.surv_rnaseq,
   time = "times",
   event = "patient.vital_status",
   variables = c("ABCC11", "ABCD4")
)
summary(BRCA_HNSC.surv_rnaseq.cut)
```

           cutpoint statistic
    ABCC11  14.8339  9.184375
    ABCD4  468.6417  1.944138

Plot cutpoint for ABCC11
------------------------

``` r
# 2. Plot cutpoint for ABCD4
# palette = "npg" (nature publishing group), see ?ggpubr::ggpar
plot(BRCA_HNSC.surv_rnaseq.cut, "ABCD4", palette = "npg")
```

    $ABCD4

![unnamed-chunk-7-1](https://cloud.githubusercontent.com/assets/6773454/20456788/d38dc7b8-ae7d-11e6-82d7-3a14f104e2b7.png)


Categorize variables
--------------------

``` r
BRCA_HNSC.surv_rnaseq.cat <- surv_categorize(BRCA_HNSC.surv_rnaseq.cut)
head(BRCA_HNSC.surv_rnaseq.cat)
```

      time event ABCC11 ABCD4
    1 3767     0   high   low
    2 3801     0   high  high
    3 1228     0    low   low
    4 1217     0   high  high
    5  158     0   high  high
    6 1477     0   high  high

remember about `cohort` variable

``` r
BRCA_HNSC.surv_rnaseq.cat <- BRCA_HNSC.surv_rnaseq.cat %>%
   mutate(cohort = BRCA_HNSC.surv_rnaseq$cohort)
head(BRCA_HNSC.surv_rnaseq.cat)
```

      time event ABCC11 ABCD4      cohort
    1 3767     0   high   low BRCA.rnaseq
    2 3801     0   high  high BRCA.rnaseq
    3 1228     0    low   low BRCA.rnaseq
    4 1217     0   high  high BRCA.rnaseq
    5  158     0   high  high BRCA.rnaseq
    6 1477     0   high  high BRCA.rnaseq

Fit survival curves and visualize
---------------------------------

### RTCGA way

``` r
RTCGA::kmTCGA(
   BRCA_HNSC.surv_rnaseq.cat, 
   times = "time",
   status = "event",
   explanatory.names = c("ABCC11", "ABCD4", "cohort"),
   pval = TRUE,
   conf.int = FALSE,
   xlim = c(0,4000)
)
```

![unnamed-chunk-10-1](https://cloud.githubusercontent.com/assets/6773454/20456789/d91d6580-ae7d-11e6-8279-8277463f098b.png)


### survminer way

``` r
library(survival)
fit <- survfit(Surv(time, event) ~ ABCC11 + ABCD4 + cohort,
               data = BRCA_HNSC.surv_rnaseq.cat)
ggsurvplot(
   fit,                     # survfit object with calculated statistics.
   risk.table = TRUE,       # show risk table.
   pval = TRUE,             # show p-value of log-rank test.
   conf.int = FALSE,        # don't show confidence intervals for 
                            # point estimaes of survival curves.
   xlim = c(0,4000),        # present narrower X axis, but not affect
                            # survival estimates.
   break.time.by = 1000,    # break X axis in time intervals by 500.
   ggtheme = theme_RTCGA(), # customize plot and risk table with a theme.
 risk.table.y.text.col = T, # colour risk table text annotations.
  risk.table.y.text = FALSE # show bars instead of names in text annotations
                            # in legend of risk table
)
```

![unnamed-chunk-11-1](https://cloud.githubusercontent.com/assets/6773454/20456792/de1e1fe8-ae7d-11e6-961b-22ff35e0e560.png)

**Comment by rg-code** [comment]
@MarcinKosinski 

Thanks a lot for prompt response, while this is extremely helpful I was trying to integrate mutation data (TCGA MAF files) with survival. I am trying to make KM plots across all TCGA cancer type at the same time by looking at a set of genes, so for example if 1000 patients from pan TCGA cohort have mutations for all the genes in my gene set, survival of those patient will be compared with the remaining patients in pan TCGA cohort to produce KM plots.

**Comment by MarcinKosinski** [comment]
Have you checked `?RTCGA:::kmTCGA` or `?RTCGA::mutationsTCGA` that are also included here

http://rtcga.github.io/RTCGA/staticdocs/kmTCGA.html
http://rtcga.github.io/RTCGA/staticdocs/mutationsTCGA.html

or have you checked this section - http://rtcga.github.io/RTCGA/Visualizations.html#kmtcga where is a KM plot for 2 cancers against mutations in TP53 gene - add more cancer types and replace the mutations in 1 gene to mutations in your genes set. Let me know how did it go : )

**Comment by rg-code** [comment]
I did have a look at `kmTCGA `and `mutationsTCGA` but neither of them allows what I am trying to do, I am trying create KM plots for merged TCGA dataset looking at mutations data. In the examples linked it is possible to use multiple cancer types and a gene set but since the dataset are not merged each cancer type is a distinct datapoint line in KM plot. 

I am looking to create KM plots with two lines using merged pan-tcga dataset where one strata of KM plots represent overall survival of patient set with mutations in specified gene set while other strata would contain patients without mutations.

**Comment by MarcinKosinski** [comment]
I'll do that for you. Examples allow that, you just need a sample modification : )

**Comment by MarcinKosinski** [comment]
@rg-code  let's consider 2 cohort types (you can easily reproduce this for all cohort type, for their names check: `?clinical` after loading RTCGA.clinical package), for which we consider their mutations information ( mutations information for all cohorts can be checked with `?mutations` after loading RTCGA.mutations package)`. I assume the considered `gene set` consist of 2 genes, you can customized this assumption for your needs. Lastly I plot KM estimates of survival curves for all considered by me cohort types, divided on 2 groups 

- patients that had mutations in all considered genes from genes set (2 genes)
- rest of the patient

code and results are below

all cancers types survival vs mutations in specified gene set
================

Data preparation
================

``` r
# installation
# source("https://bioconductor.org/biocLite.R")
# biocLite("RTCGA.clinical")
# biocLite("RTCGA.rnaseq")
library(RTCGA.clinical) # survival times
library(RTCGA.mutations) # genes' mutations

library(tidyverse) # pipes (%>%) and dplyr data munging
survivalTCGA(BRCA.clinical, OV.clinical) -> BRCA_OV.surv

mutationsTCGA(BRCA.mutations, OV.mutations) %>%
  mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) %>%
  select(bcr_patient_barcode) %>%
  unique -> patients_with_mutations_information

BRCA_OV.surv %>%
  filter(bcr_patient_barcode %in% 
           patients_with_mutations_information$bcr_patient_barcode) ->
  patients_with_survival_and_mutations_info

mutationsTCGA(BRCA.mutations, OV.mutations) %>%
    filter(Hugo_Symbol %in% c("TP53",  "PIK3CA")) %>% 
    filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% # cancer tissue
    mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12))  -> BRCA_OV.mutations

patients_with_survival_and_mutations_info %>%
    left_join(BRCA_OV.mutations,
    by = "bcr_patient_barcode") %>%
  select(times, bcr_patient_barcode, patient.vital_status, Hugo_Symbol) -> BRCA_OV.clinical_mutations

dim(BRCA_OV.surv)
```

    [1] 1674    3

``` r
dim(patients_with_mutations_information)
```

    [1] 1293    1

``` r
dim(patients_with_survival_and_mutations_info)
```

    [1] 1292    3

``` r
dim(BRCA_OV.clinical_mutations)
```

    [1] 1375    4

``` r
BRCA_OV.clinical_mutations %>%
  count(bcr_patient_barcode) -> how_many_mutations_does_patient_have
# if 2 then he has mutations in all specified gene set

BRCA_OV.clinical_mutations %>%
  left_join(how_many_mutations_does_patient_have, 
            by = "bcr_patient_barcode") %>% 
  select(times, patient.vital_status, n) %>%
  mutate(mutations_in_all_genes_from_set = ifelse(n==2, T, F)) %>%
  select(-n) -> data2viz

head(data2viz)
```

      times patient.vital_status mutations_in_all_genes_from_set
    1   259                    0                           FALSE
    2   437                    0                           FALSE
    3  1321                    0                           FALSE
    4  1463                    0                           FALSE
    5   434                    0                           FALSE
    6  1437                    0                           FALSE

RTCGA way

``` r
kmTCGA(data2viz, explanatory.names = "mutations_in_all_genes_from_set", xlim = c(0,4000))
```

![beamer-unnamed-chunk-3-1](https://cloud.githubusercontent.com/assets/6773454/20479181/8b2beebc-afdd-11e6-8800-17a7ab569912.png)


survminer way

``` r
library(survival)
fit <- survfit(Surv(times, patient.vital_status)~mutations_in_all_genes_from_set, data = data2viz)
library(survminer)
ggsurvplot(fit,
           risk.table = TRUE,
           xlim = c(0,4000),
           risk.table.y.text.col = TRUE,
                     legend = "top",
                     conf.int = FALSE, 
                     pval = TRUE,
                     risk.table.y.text = FALSE,
                     ggtheme = theme_RTCGA())
```

![beamer-unnamed-chunk-4-1](https://cloud.githubusercontent.com/assets/6773454/20479190/92226250-afdd-11e6-9b76-1ae4683d7f7e.png)

**Comment by MarcinKosinski** [comment]
how are you doing @rg-code ?

**Comment by rg-code** [comment]
Your suggested method worked perfectly, thanks a lot. You can mark the issue as closed.
